### ISSUE TITLE
Increase vertical density of new room list

### ISSUE THREAD

**Issue by turt2live** [element-hq/element-web#14099]
We've added about 12px per tile, which is fairly significant.

**Comment by niquewoodhouse** [comment]
There's definitely some opportunity to increase the vertical density, but we probably won't be able to match the previous density.  

We've added features like "message preview" that need a larger tile avatar to group the information.  

Long term, to satisfy the need for an incredibly compact room list, we could try more settings/display settings that have density options like "normal" and "compact"

**Comment by turt2live** [comment]
Blocked on UI refresh

**Comment by Felthry** [comment]
Why not just give an option to go back to the old layout? I don't use message previews and would be perfectly happy to have it back how it was.

The lack of customizability of the interface like this is more than just a nice-to-have; it's an actual accessibility issue and I would like to have it marked as more important than "nice to have (time permitting)".

**Comment by turt2live** [comment]
@Felthry maintaining two room lists is nearly impossible. We're working on this issue, and it's important not to draw conclusions from internal tracking boards which won't make sense outside of the immediate team working on the feature.

**Comment by rda0** [comment]
I would like an option to have a high density room list (maybe even twice as dense). Having smaller avatars and no previews would be a totally acceptable consequence.

**Comment by dreadnaut** [comment]
I would inject some custom CSS to increase vertical density, but the height of the panels is based on the expectation of a 32px height, so this leave large chunks of empty space. I'll post it for reference though, since it gives ~30% more rows while fitting the existing look.

Looking forward to an updated room list! 👍

``` css
.mx_RoomTile2 {
  padding: 0 0 0 4px;
}

.mx_BaseAvatar_initial,
.mx_BaseAvatar_image {
  height: 24px !important;
  width: 24px !important;
}

.mx_BaseAvatar_initial {
  line-height: 24px !important;
  font-size: 13.7px !important;
}

.mx_RoomTile2_name {
  font-size: 0.8em !important;
}
```

**Comment by Cerothen** [comment]
While I can appreciate that the priority is fully at the discretion of the developers I would like to suggest bumping up this and simultaneously the https://github.com/vector-im/riot-web/issues/14538 issue about letterboxs to ASAP. These two changes have essentially killed the client for me and I have reverted to 1.6.8 (the last version branded "Riot") as I find the changes to frustrating for my primary Matrix client.

**Comment by eternaleye** [comment]
I filed #14704 without realizing this already existed, but the info there seems useful to this discussion. First, I have a somewhat different userstyle that compacts the room list rather more strongly than what's been posted, though it presumes message previews are turned off:

```css
    /* The room list entries are way too damn big */
    section#matrixchat .mx_LeftPanel .mx_RoomList .mx_RoomTile {
        margin-bottom: 0 !important;
        padding: 1px !important;
    }

    /* Part of this is due to the enormous avatars */
    section#matrixchat .mx_LeftPanel .mx_RoomList .mx_RoomTile .mx_DecoratedRoomAvatar .mx_BaseAvatar_initial,
    section#matrixchat .mx_LeftPanel .mx_RoomList .mx_RoomTile .mx_DecoratedRoomAvatar .mx_BaseAvatar_image {
        width: 16px !important;
        height: 16px !important;
        font-size: 10.4px !important;
        line-height: 16px !important;
    }

    /* Part of this is due to slightly oversized buttons */
    section#matrixchat .mx_LeftPanel .mx_RoomList .mx_RoomTile .mx_RoomTile_menuButton,
    section#matrixchat .mx_LeftPanel .mx_RoomList .mx_RoomTile .mx_RoomTile_notificationsButton {
        width: 16px !important;
        height: 16px !important;
    }
```

This results in something more like 
![image](https://user-images.githubusercontent.com/99404/88209414-8798d900-cc07-11ea-9351-3be83276f58a.png)

Then, to fix the resizer to recognize the new size of rooms, I ran [fix-room-list-height.js](https://gist.github.com/turt2live/bca81c40117b6d5098b6b9cdaf9d3040) (courtesy of @turt2live), though in order to make it run on https://develop.element.io I had to make some tweaks (posted in a comment there). This results in something more like 
![image](https://user-images.githubusercontent.com/99404/88209666-e9f1d980-cc07-11ea-8fe6-23ba14d70e23.png)

There's still a certain amount of wasted space at the bottom of each room sublist, but hopefully this is useful to others here.

**Comment by Felthry** [comment]
@eternaleye This looks very much like what I would like to have; is there any information on how the less computer-knowledgeable of us might use this?

**Comment by eternaleye** [comment]
@Felthry Sadly, no, not really - that would require something like packaging all of this up into a Stylus userstyle for the CSS (which, admittedly, I've done [here](https://gitlab.com/snippets/1698968), though it does rather more than just the room list) and a Greasemonkey userscript for the javascript (which I briefly tried to do just now, but which didn't work). Even then it wouldn't be especially easy to use unless someone went further and did a proper WebExtension out of it.

**Comment by altsalt** [comment]
What about the option to get rid of room icons? This should reduce the vertical rhythm quite a bit.

**Comment by Cerothen** [comment]
Some people like me use the icons exclusively. I keep that panel minimized to it's narrowest form which only shows the icons.

**Comment by niquewoodhouse** [comment]
Gmail, if anyone uses it, has a settings icon that shows a lot of customizable options for the display which lets people optimize their UI for their specific use.  Maybe there's something similar Element could introduce that gives people more control over things.

<img width="300" alt="Screenshot 2020-07-28 at 09 40 52" src="https://user-images.githubusercontent.com/1587166/88641387-0a61de00-d0b7-11ea-8128-4847e9de0bca.png">

**Comment by niquewoodhouse** [comment]
That kind of customisation translates to the settings > appearance menu as something like this: 

<img width="1199" alt="#14665 1@2x" src="https://user-images.githubusercontent.com/1587166/88664930-bb777100-d0d5-11ea-831e-d93443cac3f1.png">

**Comment by t3chguy** [comment]
Given the heading is "Sidebar" will this apply to both left and right panels?

**Comment by niquewoodhouse** [comment]
I'm not sure tbh, maybe the naming isn't right.  

It might make sense more holistically to **not** have a sidebar/room list specific appearance option and **create a general Density option** that has 3 levels that impact the room list and timeline.  This could replace some of the hidden things in "advanced" like "modern layout" and help users with lots of rooms/the need for a generally compact view get it quicker.

<img width="524" alt="Screenshot 2020-07-28 at 17 25 46" src="https://user-images.githubusercontent.com/1587166/88693589-6187a300-d0f7-11ea-9c17-c96ef2abfaa8.png">

The compact view could be _something_ like @eternaleye's suggestion, the medium view could be _something_ like @dreadnaut's proposal.

**Comment by weeman1337** [comment]
> It might make sense more holistically to not have a sidebar/room list specific appearance option and create a general Density option that has 3 levels that impact the room list and timeline.

If these three options are a quick high level way to set some "advanced" options it is okay. I would like to

* have a tight packed room list holding my 25256 rooms
* but a less dense message view

**Comment by callahad** [comment]
Riffing off of @eternaleye's [comment](https://github.com/vector-im/element-web/issues/14099#issuecomment-662596500), adding the follow to his stylesheet gets rid of the wasted space for me:

```css
.mx_RoomSublist .mx_RoomSublist_resizeBox {
    height: unset !important;
    max-height: unset !important;
    min-height: unset !important;
}

.mx_RoomSublist .mx_RoomSublist_resizeBox .mx_RoomSublist_resizerHandles {
    display: none;
}
```

Note that this also hides the resize handles -- I don't use them, and they go all wonky with this change. The upside is that I don't need to inject any javascript; it all seems to just work with pure CSS tweaks.
