### ISSUE TITLE
remove listen [::]:80 from nginx/conf.d/default.conf

### ISSUE THREAD

**Issue by yxie2023** [element-hq/element-web#28486]
### Steps to reproduce

docker fails to start on linux host with ipv6 disabled.  

/docker-entrypoint.d/10-listen-on-ipv6-by-default.sh already adds this automatically if ipv6 is in fact enabled.

### Outcome

> docker run -it --rm docker.io/vectorim/element-web:latest

/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: ipv6 not available
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2024/11/18 16:03:50 [emerg] 1#1: socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)

### Operating system

Linux

### Will you send logs?

Yes

**Comment by miyurusankalpa** [comment]
why are you disabling IPv6 on the system?  build the image manually if you dont want it.

this is a user issue.

**Comment by yxie2023** [comment]
If you assume ipv6, why would you need an entire script below that tests for its existence and then explicitly enable it in nginx/conf.d/default.conf?

/docker-entrypoint.d/10-listen-on-ipv6-by-default.sh

**Comment by yxie2023** [comment]
Are you a maintainer or are you just a random ipv6 fan? 

There're good reasons to leave ipv6 disabled when not needed in 2024. Ideally element should work weather or not ipv6 is enabled.  Nginx upstream certainly seems to agree with this.

**Comment by t3chguy** [comment]
Due to recent changes this can no longer be done, as the 10-listen-on-ipv6-by-default entrypoint does not apply to templated configs, like we are now using.

**Comment by immanuelfodor** [comment]
For any other poor souls trying to fix this for an IPv4-only K8s environment: add this to your Element container definition:

```yaml
...
# Fix IPv6
# Original entrypoint script, @see: https://github.com/nginx/docker-nginx-unprivileged/blob/main/stable/alpine-slim/Dockerfile
securityContext:
  runAsUser: 0
command: ["/bin/sh"]
args:
  - -c
  - |
    echo 'Fixing IPv6..' &&
    sed -i '/^[[:space:]]*listen[[:space:]]*\[::\]:/s/^/#/' /etc/nginx/templates/default.conf.template &&
    chmod 666 /dev/stdout /dev/stderr /dev/null || true &&
    chown -R 101:101 /var/log/nginx &&
    su nginx -s /bin/sh -c "/docker-entrypoint.sh nginx -g 'daemon off;'"
...
```

1. Starts as root to execute the init script as the nginx template is owned by root but the original container then runs as nginx (switches back later)
2. Comments out the IPv6 listen port
3. Sets permissions not only to the var log folder (containing symlinks only) but also allows writing the symlink targets by other users (nginx)
4. Switches to the nginx user to execute the original entrypoint script
5. Boots up fine
