### ISSUE TITLE
Retention deleted messages keep displaying

### ISSUE THREAD

**Issue by xxfogs** [element-hq/element-web#28799]
### Prerequisites

Retention config:
```yaml
# retention, data control
retention:
    enabled: true
    default_policy:
        min_lifetime: 14d
        max_lifetime: 90d
    allowed_lifetime_min: 1d
    allowed_lifetime_max: 90d

media_retention:
    local_media_lifetime: 90d

delete_stale_devices_after: 30d
```

### Steps

1. Open Element desktop app
   - Where the homeserver has message retention enabled
2. Go to a channel with messages older than the retention period
3. Notice how some messages remain even beyond (**Oldest message 105 days ago**) the retention period (**90 + 1 days**)

![image](https://github.com/user-attachments/assets/b662596d-db31-4d60-aa98-ea8136d3dc9a)

4. Open Element Android
5. Navigate to the same channel
6. Notice how all the messages beyond the retention period are gone (**Oldest message 90 days ago**)

![image](https://github.com/user-attachments/assets/be955176-b3d4-4b28-80ed-f64551b6805a)

#### What did you expect?

I expected for all messages beyond the message retention period to be gone as it is on Element Android

#### What happened instead?

Some messages remain even beyond the retention period.
I presume this has something to do with the message cache (Security & Privacy > Encryption > Message search), however after resetting it, the messages still remained.

### Operating system

Debian GNU/Linux 12

### Application version

Element version: 1.11.89 Crypto version: Rust SDK 0.7.2 (2f872cf), Vodozemac 0.8.1

### How did you install the app?

https://element.io/download APT repository

### Homeserver

Synapse 1.121.1

### Will you send logs?

No
