### ISSUE TITLE
[1.11.90 regression] Docker image doesn't run on read-only root filesystem any more

### ISSUE THREAD

**Issue by schildbach** [element-hq/element-web#29004]
### Steps to reproduce

For security and performance reasons, I've been running the docker image on a read-only root filesystem like I do for any Docker image.

`docker run --read-only -it element-web`

This worked until up to version 1.11.89. On version 1.11.90, the process fails – see output below.

#### What did you expect?

Element-Web to start.

#### What happened instead?

```
$ docker run --read-only -it element-web
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
20-envsubst-on-templates.sh: Running envsubst on /etc/nginx/templates/default.conf.template to /etc/nginx/conf.d/default.conf
/docker-entrypoint.d/20-envsubst-on-templates.sh: line 53: can't create /etc/nginx/conf.d/default.conf: Read-only file system
```

### Operating system

Docker version 26.1.3, build 26.1.3-0ubuntu1~24.04.1

### Browser information

irrelevant

### URL for webapp

irrelevant

### Application version

1.11.90

### Homeserver

irrelevant

### Will you send logs?

No

**Comment by t3chguy** [comment]
We don't advertise read-only support, you'd need to follow the nginx docker docs for read-only support and mount any paths nginx envsubst is writing to: https://hub.docker.com/_/nginx#:~:text=Running%20nginx%20in%20read%2Donly%20mode (and the section above)

**Comment by schildbach** [comment]
Thanks for the hint. I followed this instruction years ago, but since 1.11.90 it's not correct any more.

Here is an updated `compose.yaml` that demonstrates the use of a read-only root filesystem:

```
services:
  element-web:
    build: .
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx:uid=101,gid=101
      - /etc/nginx/conf.d:uid=101,gid=101
    volumes:
      - ./element-web_config.json:/app/config.json:ro
```
