### ISSUE TITLE
Error on 1:1 call : 'RTCPeerConnection': 'stun:turn.example.com:5349?transport=udp' not a valid stun or turn URL.

### ISSUE THREAD

**Issue by BAKFR** [element-hq/element-web#32141]
### Steps to reproduce

Trying to make a call, using a private synapse server.

Server has this config:
```yaml
turn_uris:
  - "stun:turn.example.com:5349?transport=udp"
  - "stun:turn.example.com:5349?transport=tcp"
  - "turns:turn.example.com:5349?transport=udp"
  - "turns:turn.example.com:5349?transport=tcp"
turn_user_lifetime: 86400000
turn_allow_guests: false
```

It does work with URI "stun:turn.example.com:5349" and "turns:turn.example.com:5349"

The urls should be correct, according to https://matrix-org.github.io/synapse/latest/turn-howto.html

### Outcome

The call fails with this error:

```
Couldn't start call! Invalid ICE server configuration.: SyntaxError: Failed to construct 'RTCPeerConnection': 'stun:turn.example.com:5349?transport=udp' is not a valid stun or turn URL.
```

Note that the 1:1 calls were not working previously with a "Unable to access microphone" error.
I suspect that only the error message has changed.

### Operating system

Linux

### Application version

Element : 1.11.45, Olm : 3.2.14

### Will you send logs?

Yes
